# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages


bioc_packages:
     - GSEABase
     - clusterProfiler

os:
- linux
arch:
  - arm64
  - ppc64le
  - s390x
